<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Flower_Shop.Api\Flower_Shop.Api.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>aee67e9d-2fe0-4b87-9ada-d9ddd34973ff</UserSecretsId>
  </PropertyGroup>

</Project>
